### ISSUE TITLE
The reset format code is not equal to no formatting

### ISSUE THREAD

**Issue by Lodish** [CivClassic/FactoryMod#11]
When writing a book all text is in black, when this writing is converted onto a note via the printing press this text become light gray, this still works if there are no formatting codes, but if the reset code is ever used (§r) the text now become white. Within a book §r and no formatting are both black but once a note is printed the text after §r is white.

 ![image](https://user-images.githubusercontent.com/65133543/81510476-d376fa00-9309-11ea-8ad5-b53ecbd55c65.png)

![image](https://user-images.githubusercontent.com/65133543/81510564-76c80f00-930a-11ea-95e3-f4f3c036c341.png)

Because I used a §r code to remove the bold on 'Death:' the following text is white, I also used §r after the white ● to reset the colour to light gray.
 
old plates made before the 1.14 update create correct notes.

I have no idea how github works, let me know how I messed up.

**Comment by Lodish** [comment]
there's a 'more information needed' label, what information is needed?

**Comment by Maxopoly** [comment]
What is the expected behavior after a reset code?

**Comment by Lodish** [comment]
the expected behaviour is to remove formatting, it should be the same as having no format codes after the §r, for books this means the text is black either way, and that this black text becomes light gray text on notes.  (as it did on devoted, realms and classics before the update)

**Comment by Protonull** [comment]
Reset returns the string to the default colour and formatting, but that default can apparently differ between bodies of text. We've taken for granted that the default for chat and item descriptions are white and unformatted, but for books the default is different. I think we should generally move away from using the reset code as much as possible in the future since it's the only code that isn't consistent.

For reference, colour codes cancel out formatting codes, thus:

`<red><bold>Hello <white>World!`

That "World!" will *only* be white, since it cancels out the red *AND* the bold.

[Read more](https://minecraft.gamepedia.com/Formatting_codes)

**Comment by Maxopoly** [comment]
I still don't quite understand this issue, if you do you, could fix it?

**Comment by Protonull** [comment]
Yeah, it's an odd one as the issue itself is simple, that people are using `§r` when writing in books because of how it functions *in books.* But when they use a printing press to create a note, the book's text is quite literally [copy and pasted in item lore](https://github.com/CivClassic/FactoryMod/blob/master/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintNoteRecipe.java#L83), and the reset for items makes the text white. What's confusing me is how this is a new issue.. [here's a commit from *2016* with the same code](https://github.com/CivClassic/FactoryMod/blob/2ced93147092caf70aae27d842b07ac859a7a8a6/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintNoteRecipe.java#L81).

We can fix this fairly easily for *new* copies of a paper note by essentially copying [this line](https://github.com/CivClassic/FactoryMod/blob/master/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintNoteRecipe.java#L101) and changing the replaceable from black to reset. I'm not sure what we ought to do for existing paper notes though.

**Comment by Maxopoly** [comment]
It's likely some underlying behavior changing, remember Diet already fixed some other stuff regarding color that changed behavior. Idk though :man_shrugging:

**Comment by Protonull** [comment]
@Lodish Would you be content with a fix for new prints?

**Comment by Lodish** [comment]
I would be content with a fix for new prints but I think this isn't the recipe that's broken, your links show the 'create note' recipe, it is the plate creation recipe that's broken @Protonull 

old pre-update plates already work fine,the issue isn't making a note, old plates make correct notes it's the new plates that are wrong. for instance earlier the plates that made purple italic text of anything without formatting still did that after diet fixed it, you had to make new plates to do new notes, 

> changing the replaceable from black to reset

don't you need both? the point of the change to gray is black isn't allowed on notes as it's unreadable

**Comment by Lodish** [comment]
Ok it seems I was wrong, new notes from a plate made before the update aren't stacking with old notes even though no difference can be seen between the notes

**Comment by Protonull** [comment]
That's to be expected as there was a [fix](https://github.com/CivClassic/FactoryMod/commit/a4458b93fff7241b073f0eaf1af3d5eea5e8e3d5#diff-856c53a741268500cc1ff522a167ab29R103) not too long ago that added to fix formatting issues.

**Comment by Maxopoly** [comment]
But shouldn't those produce the same meta if they are visually the same?

**Comment by Protonull** [comment]
Nope, format and colour codes are just as much part of the string as the text

**Comment by Lodish** [comment]
So right now a new plate made right now and an old plate made pre-update make notes that stack together, its just old notes from the old plate that can't stack

I'm just surprised fixing the issues didn't lead to the same formatting/colour data that the old notes had.  I guess all my CivTCG cards from now on will just be 2nd edition

The cards all look how they're supposed to though so thank you

**Comment by Maxopoly** [comment]
Please report back whether this is fixed after the next restart @Lodish

**Comment by Lodish** [comment]
This is the card from pre update 
![image](https://user-images.githubusercontent.com/65133543/83171272-c762a900-a10d-11ea-8886-d9ebb3d2ca2f.png)

this is from the old design copy pasted into a new book, making a new plate and then printing new notes:

![image](https://user-images.githubusercontent.com/65133543/83171354-e4977780-a10d-11ea-804c-54ff495413ec.png)

They unfortunately don't stack together but that was expected.

Seems to be fixed to me, thanks

**Comment by Lodish** [comment]
New cards from old plate 
Old cards from old plate
New cards from new plate

these all produce identical looking cards, none of which stack. this isn't really a problem just thought it was worth noting.

**Comment by Maxopoly** [comment]
Ok, closing this then
